Feat/user
Mobydick-Team/kkm_java_server_v2 pull request #10
Opened 2023-04-04 08:34 UTC by soohyuneeee

## 개요 🎬
 - 피드백 적용
 - UserController 작성
>
<br>

## 작업 내용 🔨

- 에러코드를 ```int```에서 ```HttpStatus클래스``` 로 변경했습니다.
- ```dto```에 ```@NoArgsConstructor(access = AccessLevel.PROTECTED)```를 사용하여 무분별한 객체생성을 막아주었습니다.
- ```@Transactional``` 어노테이션을 사용하여 트랜잭션 관리를 하였습니다.
- ```accessToken```과 ```refreshToken```을 생성할 때 ```create```에서 ```generate```로 변경하였습니다.
- ```닉네임 중복확인 기능```을 추가하였습니다.
- ```회원가입 기능```을 추가하였습니다.
- ```사용자 닉네임을 변경하는 기능```을 추가하였습니다.
- ```사용자 주소를 변경하는 기능```을 추가하였습니다.
- 쓰지않는 어노테이션은 제거하였습니다.

2023-04-09 03:49 UTC, gimhanul requested changes

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/KakaoController.java
> +    }
kakao controller에 refresh token으로 access token을 재발급하는 로직을 넣는 건 컨트롤러 이름과 안 맞는 것 같아요
차라리 auth controller에 넣는 방향으로 가는 게 나을 것 같네요

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/KakaoController.java
> +public class KakaoController {
```suggestion
@RequestMapping("/auth/kakao")
@RequiredArgsConstructor
public class KakaoController {
```

이렇게 해서 Url을 한 번에 지정해줘도 좋습니다

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/KakaoController.java
> +    private final UserFacade userFacade;
```suggestion
    private final KakaoAuthService kakaoAuthService;
    private final LoginService loginService;
    private final RefreshTokenService refreshTokenService;
    private final UserFacade userFacade;
```

줄바꿈

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/KakaoController.java
> +    }
response type을 Map으로 두면 프론트 친구들이 무슨 값이 들어오는지 알기 어렵습니다 따라서 dto로 무슨 필드를 반환하는지 명시해주는 게 좋습니다

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/KakaoController.java
> +    }
이것도 마찬가지로 Object로 return하고 있즁?
그리고 비즈니스로직은 service단에서 처리합니다

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/dto/request/LoginRequest.java
> +    private String userId;
userId Long으로 사용하고 있는데 왜 String으로 받나요?
불필요한 형변환을 거칠 것 같네용

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/dto/request/LoginRequest.java
> +    private String userId;
리뷰 고맙습니다 ^__^;

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/dto/response/TokenResponse.java
> +    private Long roleId;
roleId와 isLogin이 필요한 이유가 있나요?

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/service/KakaoAuthService.java
> +        String refresh_Token = "";
카멜케이스로 통일해주세요

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/service/KakaoAuthService.java
> +        String reqURL = "https://kauth.kakao.com/oauth/token";
이렇게 바뀌지 않는 상수 코드는 static final로 만들어서 사용하면 좋습니다 (메모리상으로)

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/service/KakaoAuthService.java
> +    }
spring cloud의 feign client를 사용하면 훨씬 간편해질 것 같습니다

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/service/KakaoAuthService.java
> +        return result;
마찬가지

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/service/KakaoAuthService.java
> +        return result;
마차낙지2

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/category/domain/Category.java
> +        상의, 치마, 바지, 악세사리, 신발, 가방, 원피스, 패션소품, 기타
한글?

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/category/domain/Category.java
> +        상의, 치마, 바지, 악세사리, 신발, 가방, 원피스, 패션소품, 기타
이거 엔티티에 넣지 말고 type file을 따로 빼는 게 좋을 것 같네욤

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/domain/User.java
> +import lombok.*;
wild card는 사용하지 않는 게 좋습니다
관련 게시글 찾아보시고 intellij 세팅 바까보세용

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/domain/User.java
> +    @Column(unique = true, nullable = false, length = 38)
글자수 제한이 왜이렇게 애매한가요?
진짜 궁금해서 ㅎㅎ,

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/domain/User.java
> +    private String userId;
id가 왜 따로 있나여?

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/domain/User.java
> +    private String imgUrl;
uri와 url의 차이점을 아시나요?
그냥 번외질문임니다.

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/domain/User.java
> +    private String imgUrl;
그리고 String field는 값의 길이가 비슷비슷하다면 length를 지정해주는 게 좋습니다

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/domain/User.java
> +    private double longitude;
db mapping field에 double은 위험하다는 사실 아나요?

[참고](https://www.youtube.com/watch?v=-GsrYvZoAdA)만 하라는 뜻

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/domain/User.java
> +    @Column(name = "ROLE", length = 4, nullable = false)
왜 column이름을 ROLE로 지정하고있나용?

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/domain/User.java
> +    @Column(name = "ROLE", length = 4, nullable = false)
db는 snake case입니다

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/domain/User.java
>      private long kkm;
type이 원시타입이면 기본적으로 null이 허용되지 않아서 이럴 때는 Nullable false를 걸어주지 않아도 된다는 점 알고 계셧나요?
그치만 명시적으로 nullable false를 걸어주는 건 좋은 습관입니다~

저도 Nullable true일 때도 그냥명시해주는 편이에요 (원래 기본값이 true임)

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/exception/error/UserErrorProperty.java
> +            ;
들여쓰기뭐임?

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/facade/UserFacade.java
> +                .orElseThrow(() -> UserNotFoundException.EXCEPTION);
이렇게하면 current user가져오는 로직이 아닌 것 같은데용
security context에서 꺼내 쓰는 게 논리상 맞는 것 같네요
저기에 현재 유저가 들어있으므로...
그리고 id를 주입하는 방식으로 하면 User가 사칭을 할 수도 있어용

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/facade/UserFacade.java
> +                .orElseThrow(() ->UserNotFoundException.EXCEPTION);
```suggestion
                .orElseThrow(() -> UserNotFoundException.EXCEPTION);
```
띄어쓰기

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/facade/UserFacade.java
> +                .orElseThrow(() ->UserNotFoundException.EXCEPTION);
커맨드 옵션엘인가 누르면 코드 정렬해줌

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/facade/UserFacade.java
> +        return true;
이건 왜 굳이 true를 return하고 있나요?
그냥 한 번 이 메서드 호출하고 exception 뿌려주면 굳이 true를 return할 필요가 없습니다

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/presentation/UserController.java
> +        signUpService.execute(request,imgList.get(0));
비지니스 로직은 다 서비스로...

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/presentation/UserController.java
> +    public boolean IsNicknameExist(@PathVariable String nickname) throws Exception {
카멜케이스

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/presentation/UserController.java
> +    public boolean IsNicknameExist(@PathVariable String nickname) throws Exception {
```suggestion
    public boolean isNicknameExist(@PathVariable String nickname) throws Exception {
```

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/presentation/UserController.java
> +    @PutMapping("/update/info")
```suggestion
    }
    
    @PutMapping("/update/info")
```

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/presentation/UserController.java
> +    public void UpdateAddress(@RequestBody @Valid UpdateAddressRequest request) throws Exception{
exception은 왜 던지고있나용?

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/presentation/dto/request/SignUpRequest.java
> +    private double longitude;
아까도말햇지만 얘도 원시타입이라 null이 못들어감니다

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/service/CheckUserService.java
> +        return false;
```suggestion
        if(userFacade.isUserExistByNickName(nickname)) {
            throw UserAlreadyExistsException.EXCEPTION;
        }
        return false;
```

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/domian/user/service/CheckUserService.java
> +    @Transactional
user수정하지 않는 게 확실한 메서드에서는 readOnly option을 주면 성능이 좋아집니다

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/global/config/CorsFilterConfig.java
> +}
?
무슨 설정을 해주고 있는 건가요

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/global/config/RedisConfig.java
> +    }
비밀번호 설정 안 해주면 해킹당합니다... like me

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/global/infra/S3/service/AwsS3Service.java
> +    private String address;
properties file만들어주면 편해용

2023-04-09 03:49 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/global/security/auth/AuthDetails.java
> +
이걸 왜 또썻죠?

2023-04-09 03:50 UTC, gimhanul commented
~~왜 하셨나요? 같은 리뷰는 고치라는 뜻이 아닙니다. 진짜 궁금해서 물어보니까 답변해주세용~^^

2023-04-09 03:53 UTC, gimhanul commented
그리고 전체적으로 import 지우는 습관과 코드 정리하는 습관을 들이면 좋을 것 같아용
control option o
option command l

2023-04-09 23:09 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/domain/repository/RefreshTokenRepository.java
> +public interface RefreshTokenRepository extends JpaRepository<RefreshToken, String> {
몰랐네요 공부해보겠습니다~~^__^

2023-04-09 23:10 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/domain/repository/RefreshTokenRepository.java
> +@Repository
오호 ㅋㅋ 꿀팁 👍🏻

2023-04-09 23:15 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/KakaoController.java
> +public class KakaoController {
좋은 생각입니다.!

2023-04-09 23:16 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/KakaoController.java
> +    }
미안해요 프론트 친구들 😨
dto는 참 좋은 기능인 것 같아요 ㅎ.ㅎ

2023-04-09 23:18 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/dto/request/LoginRequest.java
> +    private String userId;
real number (실수라는 뜻)
입니다 변경하겟습니다~!

2023-04-10 01:40 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/service/KakaoAuthService.java
> +        String refresh_Token = "";
네ㅔㅔ~~~~

2023-04-10 02:07 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/global/config/CorsFilterConfig.java
> +}
아무것도 안햇어요

2023-04-10 03:08 UTC, gimhanul commented on src/main/java/com/kkm/kkm_server_v2/global/config/CorsFilterConfig.java
> +}
존재 가치가 없는 파일은 지워주세용~

2023-04-10 06:32 UTC, yongbin1 commented on src/main/java/com/kkm/kkm_server_v2/domian/user/presentation/UserController.java
> +    @PutMapping("/update/info")
모든 데이터를 업데이트 하는 것이 아니라 특정 부분의 데이터만 업데이트 하는 것이라면 PUT 메서드보다는 PATCH 메서드를 사용하는 것이 좋을 것 같습니다

2023-04-10 06:32 UTC, yongbin1 commented on src/main/java/com/kkm/kkm_server_v2/domian/user/service/SignUpService.java
> +                        .build()
Request DTO에서 toEntity 메서드를 만들어 서비스 로직을 줄이는 것은 어떤가요?

2023-04-10 06:32 UTC, yongbin1 commented on src/main/java/com/kkm/kkm_server_v2/domian/user/service/UpdateAddressService.java
> +                        .build()
Request DTO에서 toEntity 메서드를 만들어 서비스 로직을 줄이는 것은 어떤가요?

2023-04-10 06:32 UTC, yongbin1 commented on src/main/java/com/kkm/kkm_server_v2/domian/user/service/UpdateUserInfoService.java
> +                        .build()
Request DTO에서 toEntity 메서드를 만들어 서비스 로직을 줄이는 것은 어떤가요?

2023-04-10 06:32 UTC, yongbin1 commented on src/main/java/com/kkm/kkm_server_v2/global/config/properties/JwtProperties.java
> +@Setter
`@Setter` 어노테이션 보다는 `@ConstructorBinding` 어노테이션을 사용하여 생성자로 바인딩하는 것이 좋습니다.
setter로 바꿀수 있는 걸 방지? 였나
`@ConstructorBinding` 어노테이션을 사용하기 위해서는 Application.java 클래스에 `@ConfigurationPropertiesScan` 어노테이션을 넣어야합니다

2023-04-10 06:32 UTC, yongbin1 commented on src/main/java/com/kkm/kkm_server_v2/global/config/properties/JwtProperties.java
> +@Configuration
`@Configuration` 어노테이션은 없어도 됩니당ㅎ

2023-04-10 06:32 UTC, yongbin1 commented on src/main/java/com/kkm/kkm_server_v2/global/config/properties/JwtProperties.java
> +    private Long refreshTime;
시간이라는 의미를 가지는 Time 보다는 만료의 의미를 가지는 Exp가 좋을 것 같습니다.

2023-04-10 06:32 UTC, yongbin1 commented on src/main/java/com/kkm/kkm_server_v2/global/infra/S3/service/AwsS3Service.java
>          });
forEach 구문이 아닌 map 구문을 사용하여 .collect(Collectors.toList()); 로 fileNameList를 반환하게 만드는 것이 어떨까요?

```suggestion
List<String> fileNameList = multipartFile.map(item -> {
대충 s3 코드
return address+fileName;
}).collect(Collectors.toList());
```

2023-04-10 06:32 UTC, yongbin1 commented on src/main/java/com/kkm/kkm_server_v2/global/security/jwt/filter/JwtAuthenticationFilter.java
> +        UsernamePasswordAuthenticationToken authentication = new UsernamePasswordAuthenticationToken(userDetails, null, userDetails.getAuthorities());
이 로직을 JwtTokenProvider 클래스에 Authentication을 반환해주는 메서드를 만드는 것이 좋을 것 같습니다.

2023-04-10 06:32 UTC, yongbin1 commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/dto/request/LoginRequest.java
> +@AllArgsConstructor
Request 객체는 `@RequestBody` 어노테이션을 사용할 때 JSON -> DTO Object로 변환할 때 역직렬화 실패 오류가 발생할 수 있어 기본생성자를 생성해주는 `@NoArgsConsturctor` 어노테이션을 넣어줘야하는 것으로 알고 있습니다.

2023-04-10 06:32 UTC, yongbin1 commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/service/KakaoAuthService.java
> +    }
저는 WebClient도 추천합니당

2023-04-10 06:32 UTC, yongbin1 commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/service/KakaoAuthService.java
> +        return result;
낙지 맛있겠다

2023-04-15 11:11 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/user/domain/User.java
> +    private String userId;
저 아이디는 auth로 로그인 할 때 사용자에게 주어지는 아이디입니다!

2023-04-15 12:14 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/KakaoController.java
> +    }
넵!

2023-04-15 12:16 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/user/domain/User.java
>      private long kkm;
헉 몰랏네용! 감사합니다~~~!

2023-04-15 12:17 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/user/exception/error/UserErrorProperty.java
> +            ;
커맨드 옵션 엘 자주 누르겠습니다...

2023-04-15 12:20 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/user/service/CheckUserService.java
> +    @Transactional
헉 그런게 있었군요..!

2023-04-15 12:25 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/user/facade/UserFacade.java
> +        return true;
그렇네요!

2023-04-15 12:53 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/global/config/properties/JwtProperties.java
> +    private Long refreshTime;
네ㅔㅔ

2023-04-15 12:53 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/auth/presentation/dto/response/AccessTokenResponse.java
> +public class AccessTokenResponse {
냅 알겠습니당

2023-04-15 13:29 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/user/facade/UserFacade.java
> +                .orElseThrow(() -> UserNotFoundException.EXCEPTION);
헉 스정햇숩니다

2023-04-15 13:57 UTC, soohyuneeee commented on src/main/java/com/kkm/kkm_server_v2/domian/user/service/SignUpService.java
> +                        .build()
굿입니다완저니

2023-04-16 05:08 UTC, merged